/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomCodeRouteImport } from './routes/room/$code'
import { Route as ApiRoomsIndexRouteImport } from './routes/api/rooms/index'
import { Route as ApiRoomsCodeRouteImport } from './routes/api/rooms/$code'
import { Route as ApiRoomsCodeEventsRouteImport } from './routes/api/rooms/$code.events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsIndexRoute = ApiRoomsIndexRouteImport.update({
  id: '/api/rooms/',
  path: '/api/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsCodeRoute = ApiRoomsCodeRouteImport.update({
  id: '/api/rooms/$code',
  path: '/api/rooms/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsCodeEventsRoute = ApiRoomsCodeEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiRoomsCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room/$code': typeof RoomCodeRoute
  '/api/rooms/$code': typeof ApiRoomsCodeRouteWithChildren
  '/api/rooms/': typeof ApiRoomsIndexRoute
  '/api/rooms/$code/events': typeof ApiRoomsCodeEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room/$code': typeof RoomCodeRoute
  '/api/rooms/$code': typeof ApiRoomsCodeRouteWithChildren
  '/api/rooms': typeof ApiRoomsIndexRoute
  '/api/rooms/$code/events': typeof ApiRoomsCodeEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/room/$code': typeof RoomCodeRoute
  '/api/rooms/$code': typeof ApiRoomsCodeRouteWithChildren
  '/api/rooms/': typeof ApiRoomsIndexRoute
  '/api/rooms/$code/events': typeof ApiRoomsCodeEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/room/$code'
    | '/api/rooms/$code'
    | '/api/rooms/'
    | '/api/rooms/$code/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/room/$code'
    | '/api/rooms/$code'
    | '/api/rooms'
    | '/api/rooms/$code/events'
  id:
    | '__root__'
    | '/'
    | '/room/$code'
    | '/api/rooms/$code'
    | '/api/rooms/'
    | '/api/rooms/$code/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomCodeRoute: typeof RoomCodeRoute
  ApiRoomsCodeRoute: typeof ApiRoomsCodeRouteWithChildren
  ApiRoomsIndexRoute: typeof ApiRoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/': {
      id: '/api/rooms/'
      path: '/api/rooms'
      fullPath: '/api/rooms/'
      preLoaderRoute: typeof ApiRoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$code': {
      id: '/api/rooms/$code'
      path: '/api/rooms/$code'
      fullPath: '/api/rooms/$code'
      preLoaderRoute: typeof ApiRoomsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$code/events': {
      id: '/api/rooms/$code/events'
      path: '/events'
      fullPath: '/api/rooms/$code/events'
      preLoaderRoute: typeof ApiRoomsCodeEventsRouteImport
      parentRoute: typeof ApiRoomsCodeRoute
    }
  }
}

interface ApiRoomsCodeRouteChildren {
  ApiRoomsCodeEventsRoute: typeof ApiRoomsCodeEventsRoute
}

const ApiRoomsCodeRouteChildren: ApiRoomsCodeRouteChildren = {
  ApiRoomsCodeEventsRoute: ApiRoomsCodeEventsRoute,
}

const ApiRoomsCodeRouteWithChildren = ApiRoomsCodeRoute._addFileChildren(
  ApiRoomsCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomCodeRoute: RoomCodeRoute,
  ApiRoomsCodeRoute: ApiRoomsCodeRouteWithChildren,
  ApiRoomsIndexRoute: ApiRoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
